name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  cypress:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6.0.2
    - name: Run Cypress Tests
      run: docker compose up
